name: GitHub Workflow Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        run: echo "GitHub Actions is checking my repository."

      - name: Confirm workflow
        run: echo "Workflow completed successfully."
